version: 1.0.{build}
os: Visual Studio 2017
skip_tags: true
configuration: Debug
build_script:
- ps: dotnet restore ./Trappist/Trappist.sln
environment:  
  COVERALLS_REPO_TOKEN:
  secure: oI8JLO5/25+ZMrrWdVckNz5zqUysVlU+VVMBpPxZlEXaQ/A/6z544OcIs8rVhk49
branches:
  only:
    - development
    - staging
    - master
build:
  project: .\Trappist\Trappist.sln
  verbosity: minimal
test_script:
- ps: >-
   cd .\Trappist\src\Promact.Trappist.Test
- ps: >-
   opencover.4.6.589\OpenCover.Console.exe register:path32 -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test " -filter:"+[Promact.Trappist.Repository*]*" -hideskipped:File -output:opencover.xml -oldStyle
     
   C:\Users\appveyor\.nuget\packages\coveralls.net\0.8.0-unstable0013\tools\csmacnz.coveralls.exe --opencover -i opencover.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
